export const StaticText = {
    selectTransferTypeLabel: 'Select Transfer Types',
    selectOrderTypeLabel: 'Select Order Type',
    selectSupplier: 'Select Supplier',
    orderType: 'Order Type',
    routeId: 'Route Id',
    customerId: 'Customer',
    routeCode: 'Route Code',
    supplier: 'Supplier',
    stop: 'Stop#',
    transferType: 'Transfer Type',
    processDate: 'Process Date',
    refDoc: 'Ref Doc#',
    deliveryDate: 'Delivery Date',
    comments: 'Comments',
    headerUpdate: 'Header Update',
    orderIdPlaceHolder: 'Order Number',
    itemNumber: 'Product Number',
    itemNumberMandatory: 'Product Number',
    from: 'from',
    fromDateText: 'From Date',
    toDateText: 'To Date',
    date: 'Date',
    division: 'Division',
    selectDivision: 'Select Division',
    orderStatusLabel: 'Select Order Status',
    selectChangeReason: 'Select Change Reason',
    mandatorySelectChangeReason: '*Select Change Reason',
    orderStatus: 'Order Status',
    searchQuery: 'Please enter search criteria to fetch the results!',
    dateType: 'Select Date Type',
    details: 'Details',
    logistics: 'Logistics',
    ok: 'OK',
    emailId: 'Email Id',
    userId: 'User Name',
    editHeader: 'Header Details',
    nodataFound: 'No data found!',
    editSubmitText: 'Submit',
    editCancelText: 'Cancel',
    headerUpDateLabel: 'Bulk Update',
    downlaodcsvReport: 'Download CSV Report',
    exportcsvReport: 'Export to CSV',
    customerGroup: 'Customer Order Group',
    allocationUpDown: 'Select Allocation',
    allocationReviewLabel: 'Allocation Review',
    substitutionReviewLabel: 'Substitution Review',
    substitutionReviewQuantity: 'Qty',
    subDescription: 'Desc',
    customerGroupId: 'COG',
    groupName: 'Group Name',
    groupType: 'Group Type',
    itemDescription: 'Product Description',
    itemPackSize: 'Product Pack Size',
    maxItemOrderQty: 'Max Product Quantity',
    minItemOrderQty: 'Min Product Quantity',
    groupDescription: 'Group Description',
    attributeSelectText: 'Select Attribute',
    supplierAttributeLabel: 'Supplier',
    itemIdLabel: 'Product',
    subsDescription: 'Substitution Desc',
    maxOrderQty: 'Max Order Quantity',
    itemAttributeLabel: 'Product Number',
    divisionAttributeLabel: 'Division Number',
    customerAttributeLabel: 'Customer',
    cogAttributeLabel: 'COG',
    crgLabel: 'CRG',
    save: 'Save',
    cancel: 'Cancel',
    processingDate: 'Processing Date',
    effectiveDate: 'Effective Date',
    endDate: 'End Date',
    expiryDate: 'Expiry Date',
    releaseDate: 'Release Date',
    sourceOfSupply: 'Source Of Supply',
    SOSSearch: 'SOS Search',
    addSupplierCustomerRelationship: 'Add SOS Relationship',
    editSupplierCustomerRelationship: 'Edit SOS Relationship',
    editPermissions: 'Edit Permissions',
    priority: 'Priority',
    create: 'Create',
    reset: 'Reset',
    SubstitutionId: 'Substitution Id',
    substitutionDesc: 'Substitution Description',
    substituteProductDesc: 'Substitute Product Description',
    quantityAdjsmt: 'Quantity Multiplier',
    changeReason: 'Change Reason',
    searchText: ' Name, User Id or Email Id',
    groupSearchHeading: 'Search Group',
    addGroupLabel: 'Add Group',
    editGroupLabel: 'Edit Group',
    assignUsers: 'Assign Users to Group',
    addUserLabel: 'Add User',
    userSearch: 'Search User',
    firstName: 'First Name',
    lastName: 'Last Name',
    invitaionEmail: 'Send invitation email',
    addGroup: 'Add Group',
    editUserLabel: 'Edit User',
    allocationPercentChange: 'Percentage Change',
    allocationUniformDistribution: 'Uniform Distribution',
    allocationQtyAdjustment: 'Adjusted Quantity',
    allocationRoundAndRobin: 'Round Robin + Demand Distribution',
    requiredLabel: 'Required',
    allocationModalHeadingText: 'Quantity Adjustment',
    substitutionModalHeadingText: 'Substitute Product',
    cancellationModalHeadingText: 'Cancel Product',
    submitBtnText: 'Submit',
    cancelBtnText: 'Cancel',
    reviewBtnText: 'Review',
    groupNotFound: 'Group not found',
    orderedQty: 'Ordered Quantity',
    updatedQty: 'Updated Quantity',
    userUpdatedQty: 'User Updated Quantity',
    updateBtnText: 'Update',
    sosRelationshipSavedSuccessfully: 'SOS relationship submitted successfully',
    groupSavedSuccessfully: 'Group Saved Successfully',
    itemOrderQtyText: 'Product Order Qunatity',
    autoAllocationText: 'Auto Allocation',
    palletRoundingText: 'Pallet Rounding',
    palletRoundDownText: 'Pallet Round Down %',
    palletRoundUpText: 'Pallet Round Up %',
    caseRoundingText: 'Case Rounding',
    caseRoundDownText: 'Case Round Down %',
    caseRoundUpText: 'Case Round Up %',
    maxQtyText: 'Max Product Quantity',
    minQtyText: 'Min Product Quantity',
    allocationTooltipHeadingText: 'Product Allocation',
    substitutionTooltipHeadingText: 'Product Substitution',
    cancellationTooltipHeadingText: 'Product Cancellation',
    orderMonitor: 'Order Monitor',
    Rdiv: 'Rdiv',
    customerid: 'Customer Id',
    supplierid: 'Supplier Id',
    status: 'Status',
    cutoffdatetime: 'Cut-Off Date/Time',
    tog: 'TOG',
    orderid: 'Order Id',
    cust: 'Cust#',
    supplierId: 'Supplier Id',
    weight: 'Weight',
    cubes: 'Cubes',
    case: 'Case',
    pallet: 'Pallet',
    fileretrigger: 'File Retrigger',
    filename: 'Filename',
    downloadtype: 'Download Type',
    processextractdate: 'Process Extract Date',
    autoholding: 'Auto Holding',
    crg: 'CRG',
    selectCustomerType: 'Select Customer Type',
    scheduleId: 'Schedule Id',
    selectScheduleId: 'Select Schedule Id',
    scheduleDescription: 'Schedule Description',
    searchScheduleId: 'Search Schedule Id',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thrusday: 'Thrusday',
    friday: 'Friday',
    saturday: 'Saturday',
    attribute: 'Attribute',
    attributeValue: 'Attribute Value',
    errorCode: 'Error Code',
    errorDescription: 'Error Description',
    dateTime: 'Date and Time',
    severity: 'Severity',
    active: 'Active',
    supplierRequired: '*Supplier',
    customerOrderGroup: 'Customer Order Group',
    originalOrderQunatity: 'Original Qty',
    originalProductId: 'Original Product No',
    lastUpdatedQuantity: 'Last Updated Qty',
    autoAllocatedQty: 'Auto Allocated Qty',
    autoAllocation: 'Auto Allocation',
    modifierUserID: 'Modifier By',
    modifiedDate: 'Modified Date',
    sysAdjustedItemQty : 'System Adjusted Qty',
    userAdjustedItemQty : 'User Adjusted Qty',
    distributionCenterId : 'Distribution Center Id',
    releaseWindow: 'Release Window',
    routeCodeLabel: 'RT',
    retrictedOrderDayLabel: 'RO',
    offsetDayLabel: 'OS',
    searchInboundScheHeading: 'Search Inbound Schedule',
    releaseSchedule: 'Release Schedule',
    physicalWarehouseOption : 'Select Physical Whse',
    processDay: 'Process Day',
    ChangeProductId: 'Change Product No',
    retailDivision : 'Select Retail Division',
    toEffectiveDate : 'To Effective Date',
    fromEffectiveDate : 'From Effective Date',
    supplierDepartment: 'Supplier Department',
    manageConfig : 'Manage Config',
    crgField: 'Customer Release Group'
};
