export const OrdersConfig = {
    maxAdditionOfItemsInSingleOrder: 50,
    createOrderTypes: ['rush', 'transfer'],
    perPagesRecordsTobeDisplayed: [5, 10, 25, 50, 100],
    numberOfPagesOptionsToBeDispalyed: 5,
    manageOrderStatus: [201, 202, 204, 205, 208, 210, 211, 212, 213],
    noStandingOrderTypes: [101, 102, 103, 105, 106],
    editOrderStatus: { 202: [204, 205], 205: [204, 213] },
    bulkUpdateStatus: [204, 205, 213],
    allocationSearchStatus: [202],
    cancellationSearchStatus: [202,205],
    allocationSearchOrderType: [101, 102, 103],
    orderEditContextType: ['OEDIT'],
    bulkUpdateContextType: ['BULKU'],
    itemCancellationContextType: ['ITCAN'],
    orderSubstitutionContextType: ['OSUBS'],
    orderAllocationContextType: ['OALOC'],
    systemContextType: ['SYSTM'],
    autoHoldingCreateContextType: ['OEDIT'],
    createOrderTypesRealease: ['regular', 'firm'],
    searchTogAssociation: ['reg', 'sep', 'all'],
    cloneInboundSchedule: ['regular', 'firm', 'all'],
    searchInboundScheduleOrderTypes: ['regular', 'firm'],
    inboundScheduleOrderType: [101, 103, '101,103'],
    createOrderTypesRealeaseSchedule: ['all', 'regular', 'firm', 'separate', 'rush'],
    createTypesRealeaseSchedule: [101, 102, 103],
    scrollLoadDataLimit : 25,
    totalThrushHoldDataLimit : 100
}